### ISSUE TITLE
Throw error when 'major', 'minor' or 'patch' is not specified?

### ISSUE THREAD

**Issue by thsbrown** [AlexStormwood/UnityAutomatedSemver#1]
The action looks really great, but as far as I can tell by looking at the code it doesn't throw an error when 'major', 'minor' or 'patch'  specifically isn't specified. Because of this, I think it can lead to unpredictable behavior when trying to build it into other workflows.

This is due to the fact that if there is any sort of incorrect input such as "mjr", or anything else for that matter it would lead to strange results.

I think this would be quite simple to fix by just adding `core.setFailed("major, minor or patch must be specified");` to the default case in your switch statement.

https://github.com/AlexHolderDeveloper/UnityAutomatedSemver/blob/4ae3f01af014984baf49ed49917f5c2cecb2948e/src/index.js#L57-L75

**Comment by AlexStormwood** [comment]
Thankyou for picking this up - can you tell that this was a "hello world"-type Github Action? Some common functionality & quality control is definitely lacking here. Will merge PRs as they come through!

**Comment by thsbrown** [comment]
Haha all good man! I've definitely been there and very I'm much in the learning phase of github actions. 

It's quite incredible what you can automate with them though.

Thanks so much for the initial work. I already have it running on one of my workflows for my game. I also created this github action to pair with yours if you're interested :). https://github.com/marketplace/actions/unity-mobile-build-number-bumper
