### ISSUE TITLE
output semver-number outputs "bundleVersion: someNumber" instead of just "someNumber"

### ISSUE THREAD

**Issue by thsbrown** [AlexStormwood/UnityAutomatedSemver#4]
I think it's much more intuitive to output just the new semantic version number instead of prefacing it with "bundleVersion: ".

I actually went ahead and already made the change on my end and can pull the request if you want me to :). The issue is it's building on the changes of the other to prs I have made (#3 #2).  Because of this it might make more sense to pull those in first before I pr granted you like my changes.

Cheers!

P.S. Here is the code reference of what I'm talking about

https://github.com/AlexHolderDeveloper/UnityAutomatedSemver/blob/4ae3f01af014984baf49ed49917f5c2cecb2948e/src/index.js#L80-L81

**Comment by AlexStormwood** [comment]
That sounds great! Happy for PRs to come through 😀

**Comment by thsbrown** [comment]
Sweet i'll send the pr through!

**Comment by thsbrown** [comment]
Ah man, I must have been tired when I wrote that as I guess I snuck this change in [this commit](https://github.com/AlexHolderDeveloper/UnityAutomatedSemver/pull/3/commits/f061a8367fcb1dc1ecf958dc6eb41d24131bac82) & thus [this pr](https://github.com/AlexHolderDeveloper/UnityAutomatedSemver/pull/3).

So as it stands now it will output just the semantic version.

Example

`1.0.0` instead of `bundleVersion: 1.1.0`
