### ISSUE TITLE
Trailing 0 Keeps adding more 0's

### ISSUE THREAD

**Issue by Warhammer4000** [AlexStormwood/UnityAutomatedSemver#6]
I enabled the ms-store trailing zero. And after each workflow run this is what is happening. It keeps adding new zeroes. 

![image](https://github.com/AlexStormwood/UnityAutomatedSemver/assets/12670678/fbcbf01f-c692-4ac1-8052-c9985bcc2a5f)

It should be something like {major.minor.patch.store}

**Comment by AlexStormwood** [comment]
Can you show any logs from when you're running the workflow?

This workflow is supposed to build a semver string with `major.minor.patch` and then add a trailing zero to it -- so there could maybe be something wrong with how it's parsing in semver strings from the project? (eg. maybe patch has a bad value?)

Especially interested in the output of the "Semver is now: " log that you should see in your action logs.

```js

            console.log(`Semver is now: ${JSON.stringify(semverAsObj)}`);

            // 8. Convert semver obj back into string
            let newSemver = `${semverAsObj.major}.${semverAsObj.minor}.${semverAsObj.patch}`;

            let shouldAddTrailingDotZero = core.getInput("should-add-ms-store-trailing-zero") === "true";

            if (shouldAddTrailingDotZero) {
                newSemver += ".0";
            }
```

**Comment by AlexStormwood** [comment]
Ah actually, I think I may have spotted the issue -- the regex used when inserting the newSemver string back into the project settings file was only searching for 3 version numbers regardless of the trailing zero setting. So it would've worked once and then stuffed up in all future runs.

I don't actually have a Unity project on hand to try out the fix so I'm just gonna merge a fix and hope for the best - but you may still have to manually edit your version in the ProjectSettings.asset file first to get things back on track.


Please let me know how you go.
```yml         
- name: Unity Automated Semver
  uses: AlexStormwood/UnityAutomatedSemver@v1.1.1
``` 


(And great timing on raising this issue, just got back from a renaissance fair and have plenty of energy to burn :D )

**Comment by Warhammer4000** [comment]
Just updated and ran the workflow it works as expected now. Thanks a lot !
![image](https://github.com/AlexStormwood/UnityAutomatedSemver/assets/12670678/bb4df1a3-69c1-46d3-8d40-b00413a8bfff)
